# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DependencyTag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('restricted_access', models.BooleanField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('future_plans', models.TextField(blank=True, null=True)),
                ('business_tags', models.ManyToManyField(blank=True, related_name='tools', to='app.BusinessTag')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sesa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('DN', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='update',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.User'),
        ),
        migrations.AddField(
            model_name='tool',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_created', to='app.User'),
        ),
        migrations.AddField(
            model_name='tool',
            name='dependency_tags',
            field=models.ManyToManyField(blank=True, related_name='tools', to='app.DependencyTag'),
        ),
        migrations.AddField(
            model_name='tool',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_developed', to='app.User'),
        ),
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_owned', to='app.User'),
        ),
    ]
